### ISSUE TITLE
Chart assumes stable IP address

### ISSUE THREAD

**Issue by sebastianvoss** [confluentinc/cp-helm-charts#240]
As the `cp-kafka`is using `POD_IP` in `KAFKA_ADVERTISED_LISTENERS` consumers are failing when a broker gets a new IP assigned (e.g. on restarts). Wouldn't it be better to use the headless service of the broker?
```
${POD_NAME}.{{ template "cp-kafka.fullname" . }}-headless.${POD_NAMESPACE}:9092
```
If so, I'm happy to submit a merge request for this.

**Comment by qshao-pivotal** [comment]
I thought consumers can use bootstrap-servers with current setups. https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/templates/tests/canary-pod.yaml#L26

But I never tested consumer running with restart of brokers being triggered. Could you elaborate more on the test case and observations?

**Comment by sebastianvoss** [comment]
@qshao-pivotal bootstrap-servers is used for the initial connection to one of the brokers. After the client discovered the brokers the endpoint which is configured as advertised listener will be exchanged. From this point the client will just use those endpoints. If one of the brokers changes the IP (e.g. on pod restart in Kubernetes) the client still uses the old IP address. Using DNS names instead of IP addresses should mitigate this issue.

**Comment by nixsticks** [comment]
@sebastianvoss @qshao-pivotal I came here to see if anyone had added this issue as we are running into it as well. I saw issues with our Java producer not reconnecting when the pod IP changes, and this lasted for 20+ minutes until I killed the producer pods. I recreated this several times and each time it was fixed only when I killed the producer and restarted.

**Comment by nixsticks** [comment]
A similar fix to the suggested headless service use might then also be required for external clients using the nodeports, should the brokers be moved to different hosts within the cluster.

**Comment by qshao-pivotal** [comment]
@nixsticks  @sebastianvoss Thanks a lot for the explanation. Definitely would love to see a PR to fix this! :)

**Comment by nixsticks** [comment]
Hey @sebastianvoss @qshao-pivotal ,

I was doing some testing with Sebastian's proposed fix and found that using a DNS name for the broker was not helping, as the original IP address to which it resolved appeared to be cached. I believe this will be fixed in 2.1.1 with https://issues.apache.org/jira/browse/KAFKA-7890 (and/or https://issues.apache.org/jira/browse/KAFKA-7755 for the case where we use DNS), but until then I don't think there is an easy solution without something like restarting the client. Please let me know if I am mistaken.

**Comment by sebastianvoss** [comment]
@nixsticks You are right about the bug in the latest version of the Kafka Java client (KAFKA-7755). This is already resolved and will be part of the next release end of Feb. But to benefit from this solution we still need to use DNS names in `cp-kafka`. Otherwise clients will still be stuck when the broker gets restarted and receives a new IP.

**Comment by qshao-pivotal** [comment]
Relying on DNS is better than replying on IP, so I would say let's make the change to`cp-kafka` anyway. :) Thanks for the investigation!

**Comment by nixsticks** [comment]
@sebastianvoss Right, but won't KAFKA-7890 fix the issue where clients get stuck when the broker receives a new IP without using DNS? I believe KAFKA-7755 fixes the issue where IPs change underneath the DNS name but KAFKA-7890 fixes the issue where IP changes without using DNS or the DNS name itself changes.

I agree though with @qshao-pivotal that we should change it anyway.

**Comment by sebastianvoss** [comment]
AFAIK when advertised listeners contain the plain IP address the Kafka client has no way to find out the new IP. Technically this is only possible when we use DNS names which gives the client a way to re-resolve the new IP address (depends on the fix addressed by KAFKA-7755).

I submitted a pull request to use DNS of the headless service.

**Comment by nixsticks** [comment]
Oh interesting, @sebastianvoss. Thanks for the explanation.

**Comment by nixsticks** [comment]
For your interest @sebastianvoss: 2.1.1 was released yesterday, and I tested the current chart with the MirrorMaker Java producer. It seems able to resolve the new IP address without DNS (in my cluster, advertised listeners = pod IP). I will look around in the code to confirm this if I get some time, just out of curiosity on my own part.

**Comment by sebastianvoss** [comment]
@nixsticks, that is interesting. I'm wondering where it gets the new IP from. The only thing I could think of, it might fall back to `bootstrap.servers` to reinitiate? If you find it out, keep us posted.

**Comment by DaveSlinn** [comment]
We have deployed kafka using the latest helm chart, and are just digging into communicating with kafka from external to kubernetes and that has us looking into the advertised listeners setting. We noticed that the new helm chart is not putting a KAFKA_ADVERTISED_LISTENERS environment variable in the kafka stateful set anymore.  Out 5.0.1 cluster stateful set has it (when it was still using the POD_ID value and template).  Here is a comparison of the section of the deployed stateful set yaml from k8s:

![image](https://user-images.githubusercontent.com/18301427/57542778-cf3b8980-730f-11e9-8a80-070bf84d48cc.png)

As you can see, the left side has that variable, the right side does not. Am I miss understanding something, or should that variable still be present, even though it's now using the headless service?

**Comment by sebastianvoss** [comment]
`KAFKA_ADVERTISED_LISTENERS` is still present but set at runtime using an `export` command (because the values it depends on can only be fetched this way). If you want to externally access your cluster you can configure this in `values.yaml`, e.g:

```
nodeport:
  enabled: true

configurationOverrides:
  "advertised.listeners": |-
   EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
```

**Comment by DaveSlinn** [comment]
Perfect. Worked a treat.

**Comment by DaveSlinn** [comment]
However, we are now trying to deploy a second kafka instance and also expose it externally from k8s, but are getting port conflicts because those ports are in use from the first cluster.  We tried overriding the values on the helm install using --set cp-kafka.nodeport.firstListenerPort=32090, but this doesn't change advertised.listeners value.  Is there a way to modify the values.yaml to use the firstListenerPort value?  We tried a few ways to make this more dynamic with the override but our knowledge of helm syntax prevented us from getting anything working.  Can you reference a value in the values.yaml from another location within the same file?

**Comment by michelverheijen** [comment]
@DaveSlinn, see https://github.com/confluentinc/cp-helm-charts/issues/263
